"""Initial migration

Revision ID: 241cb24aa24d
Revises: 39456dc0531e
Create Date: 2025-05-13 14:42:35.945893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241cb24aa24d'
down_revision: Union[str, None] = '39456dc0531e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permitions', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'permitions', ['retail_id'])
    op.add_column('persons', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'persons', ['retail_id'])
    op.add_column('plan_work_times', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'plan_work_times', ['retail_id'])
    op.add_column('planogram_orders', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'planogram_orders', ['retail_id'])
    op.add_column('posts', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['retail_id'])
    op.add_column('products', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'products', ['retail_id'])
    op.add_column('shelvings', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'shelvings', ['retail_id'])
    op.add_column('shift_assignments', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'shift_assignments', ['retail_id'])
    op.add_column('store_shifts', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'store_shifts', ['retail_id'])
    op.add_column('stores', sa.Column('retail_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'stores', ['retail_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_column('stores', 'retail_id')
    op.drop_constraint(None, 'store_shifts', type_='unique')
    op.drop_column('store_shifts', 'retail_id')
    op.drop_constraint(None, 'shift_assignments', type_='unique')
    op.drop_column('shift_assignments', 'retail_id')
    op.drop_constraint(None, 'shelvings', type_='unique')
    op.drop_column('shelvings', 'retail_id')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'retail_id')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'retail_id')
    op.drop_constraint(None, 'planogram_orders', type_='unique')
    op.drop_column('planogram_orders', 'retail_id')
    op.drop_constraint(None, 'plan_work_times', type_='unique')
    op.drop_column('plan_work_times', 'retail_id')
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_column('persons', 'retail_id')
    op.drop_constraint(None, 'permitions', type_='unique')
    op.drop_column('permitions', 'retail_id')
    # ### end Alembic commands ###
