"""Initial migration

Revision ID: 2838a3a5429f
Revises: 8f1a1367e22c
Create Date: 2025-05-05 16:41:15.272595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2838a3a5429f'
down_revision: Union[str, None] = '8f1a1367e22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_posts', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_posts', 'count')
    # ### end Alembic commands ###
