"""Initial migration

Revision ID: 2b9b91c22243
Revises: 66da24c91d3d
Create Date: 2025-05-08 08:19:00.592541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9b91c22243'
down_revision: Union[str, None] = '66da24c91d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realogram_detections', sa.Column('right_product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'realogram_detections', 'products', ['right_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realogram_detections', type_='foreignkey')
    op.drop_column('realogram_detections', 'right_product_id')
    # ### end Alembic commands ###
