"""Initial migration

Revision ID: 2e2e30348d80
Revises: f4cc73e9f4e4
Create Date: 2025-05-02 17:39:20.574718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2e30348d80'
down_revision: Union[str, None] = 'f4cc73e9f4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realogram_detections', sa.Column('conf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realogram_detections', 'conf')
    # ### end Alembic commands ###
