"""Initial migration

Revision ID: 66da24c91d3d
Revises: 4abab22f3513
Create Date: 2025-05-07 20:06:39.183924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66da24c91d3d'
down_revision: Union[str, None] = '4abab22f3513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realogram_detections', sa.Column('elimination_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realogram_detections', 'elimination_time')
    # ### end Alembic commands ###
