"""Initial migration

Revision ID: 69a25cb257ec
Revises: f3d12d0c02b8
Create Date: 2025-05-04 16:06:57.536182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a25cb257ec'
down_revision: Union[str, None] = 'f3d12d0c02b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calibration_boxes_calibration_id_fkey', 'calibration_boxes', type_='foreignkey')
    op.create_foreign_key(None, 'calibration_boxes', 'calibrations', ['calibration_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('calibrations_planogram_id_fkey', 'calibrations', type_='foreignkey')
    op.create_foreign_key(None, 'calibrations', 'planograms', ['planogram_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('embeddings_model_id_fkey', 'embeddings', type_='foreignkey')
    op.drop_constraint('embeddings_image_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'embedding_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'embeddings', 'product_images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('planogram_products_planogram_id_fkey', 'planogram_products', type_='foreignkey')
    op.create_foreign_key(None, 'planogram_products', 'planograms', ['planogram_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_boxes_planogram_product_id_fkey', 'product_boxes', type_='foreignkey')
    op.create_foreign_key(None, 'product_boxes', 'planogram_products', ['planogram_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('realogram_snapshots_planogram_id_fkey', 'realogram_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'realogram_snapshots', 'planograms', ['planogram_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realogram_snapshots', type_='foreignkey')
    op.create_foreign_key('realogram_snapshots_planogram_id_fkey', 'realogram_snapshots', 'planograms', ['planogram_id'], ['id'])
    op.drop_constraint(None, 'product_boxes', type_='foreignkey')
    op.create_foreign_key('product_boxes_planogram_product_id_fkey', 'product_boxes', 'planogram_products', ['planogram_product_id'], ['id'])
    op.drop_constraint(None, 'planogram_products', type_='foreignkey')
    op.create_foreign_key('planogram_products_planogram_id_fkey', 'planogram_products', 'planograms', ['planogram_id'], ['id'])
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_image_id_fkey', 'embeddings', 'product_images', ['image_id'], ['id'])
    op.create_foreign_key('embeddings_model_id_fkey', 'embeddings', 'embedding_models', ['model_id'], ['id'])
    op.drop_constraint(None, 'calibrations', type_='foreignkey')
    op.create_foreign_key('calibrations_planogram_id_fkey', 'calibrations', 'planograms', ['planogram_id'], ['id'])
    op.drop_constraint(None, 'calibration_boxes', type_='foreignkey')
    op.create_foreign_key('calibration_boxes_calibration_id_fkey', 'calibration_boxes', 'calibrations', ['calibration_id'], ['id'])
    # ### end Alembic commands ###
