"""Initial migration

Revision ID: 8291c7854385
Revises: 62622e6be023
Create Date: 2025-05-02 10:39:12.873050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8291c7854385'
down_revision: Union[str, None] = '62622e6be023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planograms', sa.Column('img_src', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planograms', 'img_src')
    # ### end Alembic commands ###
