"""Initial migration

Revision ID: 8f1a1367e22c
Revises: 69a25cb257ec
Create Date: 2025-05-04 18:39:20.665770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1a1367e22c'
down_revision: Union[str, None] = '69a25cb257ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_product_id_fkey', 'product_images', 'products', ['product_id'], ['id'])
    op.drop_column('persons', 'password_hash')
    op.drop_column('persons', 'is_active')
    # ### end Alembic commands ###
