"""Initial migration

Revision ID: f21f31201fe5
Revises: 2838a3a5429f
Create Date: 2025-05-05 20:09:57.020989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21f31201fe5'
down_revision: Union[str, None] = '2838a3a5429f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permitions',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permitions_id'), 'permitions', ['id'], unique=False)
    op.create_table('post_permitions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('permition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permition_id'], ['permitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_permitions_id'), 'post_permitions', ['id'], unique=False)
    op.add_column('persons', sa.Column('is_store_worker', sa.Boolean(), nullable=True))
    op.drop_column('persons', 'is_worker')
    op.drop_column('posts', 'is_administrative')
    op.drop_column('posts', 'is_regular')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_regular', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('is_administrative', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('persons', sa.Column('is_worker', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('persons', 'is_store_worker')
    op.drop_index(op.f('ix_post_permitions_id'), table_name='post_permitions')
    op.drop_table('post_permitions')
    op.drop_index(op.f('ix_permitions_id'), table_name='permitions')
    op.drop_table('permitions')
    # ### end Alembic commands ###
