"""Initial migration

Revision ID: f3d12d0c02b8
Revises: 2e2e30348d80
Create Date: 2025-05-02 18:08:53.857006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d12d0c02b8'
down_revision: Union[str, None] = '2e2e30348d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_regular', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('is_administrative', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_administrative')
    op.drop_column('posts', 'is_regular')
    # ### end Alembic commands ###
